spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${MYSQL_USER:claimpaws}
    password: ${MYSQL_PASSWORD:local-dev-only}
  rabbitmq:
    username: ${RABBITMQ_USERNAME:claimpaws}
    password: ${RABBITMQ_PASSWORD:local-dev-only}
