server:
  port: 8080

spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
    gateway:
      server:
        webflux:
          routes:
            - id: identity
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health
