spring:
  config:
    activate:
      on-profile: docker
    import: "optional:nacos:${spring.application.name}.yaml?server-addr=${NACOS_SERVER_ADDR:nacos:8848}"
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yaml

server:
  port: 8080
